import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLang { en, tr, de }

final appLang = ValueNotifier<AppLang>(AppLang.en);

Future<void> initLang() async {
  final prefs = await SharedPreferences.getInstance();
  final saved = prefs.getString('app_lang') ?? 'en';
  appLang.value = AppLang.values.firstWhere(
    (e) => e.name == saved,
    orElse: () => AppLang.en,
  );
}

String get kDefaultAnalysisPrompt => switch (appLang.value) {
  AppLang.tr => "Lütfen bu soruyu adım adım, mantığını ve önemli püf noktalarını detaylandırarak çözer misin?",
  AppLang.de => "Könnten Sie diese Frage bitte Schritt für Schritt lösen und dabei die Logik und die wichtigsten Punkte detailliert erklären?",
  _ => "Could you please solve this question step by step, detailing the logic and important key points?",
};

String get kDefaultSimilarPrompt => switch (appLang.value) {
  AppLang.tr => "Lütfen bu soruya konu, yapı ve zorluk seviyesi bakımından çok benzer, 5 şıklı yeni bir test sorusu üretip altına çözümünü yazar mısın?",
  AppLang.de => "Könnten Sie bitte eine neue Testfrage mit 5 Antwortmöglichkeiten generieren, die dieser Frage in Bezug auf Thema, Struktur und Schwierigkeitsgrad sehr ähnlich ist, und die Lösung darunter schreiben?",
  _ => "Could you please generate a new 5-option test question that is very similar to this question in terms of topic, structure, and difficulty, and write the solution below?",
};

const _trMap = <String, String>{
  'Home': 'Ana Menü', 'Settings': 'Ayarlar', 'Select Language': 'Dil Seçimi',
  'App Language': 'Uygulama Dili', 'ARTIFICIAL INTELLIGENCE': 'YAPAY ZEKA',
  'Delete All Questions': 'Tüm Soruları Sil', 'No Questions': 'Soru Yok',
  'Add First Question': 'İlk Soruyu Ekle',
  'Add questions you couldn\'t solve here.': 'Çözemediğin soruları buraya ekle.',
  'math': 'Matematik', 'physics': 'Fizik', 'chemistry': 'Kimya', 'biology': 'Biyoloji',
  'nativeLang': 'Türkçe', 'literature': 'Edebiyat', 'history': 'Tarih', 'geography': 'Coğrafya',
  'philosophy': 'Felsefe', 'foreignLang': 'İngilizce',
  'easy': 'Kolay', 'medium': 'Orta', 'hard': 'Zor',
  'Question': 'Soru', 'Days': 'Gün', 'No data': 'Veri yok',
  'Review Questions': 'Soruları Gözden Geçir',
  'questions listed': 'soru listeleniyor', 'Filter': 'Filtrele',
  'No questions found matching these filters.': 'Bu filtrelere uygun soru bulunamadı.',
  'Delete Question': 'Soruyu Sil',
  'Are you sure you want to delete this question?': 'Bu soruyu silmek istediğinize emin misiniz?',
  'Delete': 'Sil', 'Cancel': 'Vazgeç',
  'LANGUAGE': 'DİL', 'Analysis Prompt': 'Analiz Promptu',
  'Similar Question Prompt': 'Benzer Soru Promptu',
  'DATA MANAGEMENT': 'VERİ YÖNETİMİ', 'Saved Questions Count': 'Kayıtlı Soru Sayısı',
  'Export': 'Dışa Aktar', 'Import': 'İçe Aktar', 'DANGER ZONE': 'TEHLİKELİ BÖLGE',
  'This action cannot be undone.': 'Bu işlem geri alınamaz.', 'OK': 'Tamam',
  'Reset to Default': 'Varsayılana Dön', 'Save': 'Kaydet',
  'All questions deleted.': 'Tüm sorular silindi.',
  'Reverted to default prompt.': 'Varsayılan prompta dönüldü.',
  'Prompt saved.': 'Prompt kaydedildi.',
  'An error occurred during export.': 'Export sırasında bir hata oluştu.',
  'Invalid file. Please select a valid ZIP.': 'Geçersiz dosya. Lütfen doğru bir ZIP seçin.',
  'An error occurred during import.': 'Import sırasında bir hata oluştu.',
  'Add New Question': 'Yeni Soru Ekle', 'Edit Question': 'Soruyu Düzenle',
  'QUESTION PHOTO': 'SORU FOTOĞRAFI', 'Tap to add photo': 'Fotoğraf eklemek için dokun',
  'Take with Camera': 'Kamera ile Çek', 'Select from Gallery': 'Galeriden Seç',
  'Add Photo': 'Fotoğraf Ekle', 'SUBJECT': 'DERS', 'DIFFICULTY': 'ZORLUK',
  'CORRECT ANSWER': 'DOĞRU CEVAP', 'NOTE (OPTIONAL)': 'NOT (İSTEĞE BAĞLI)',
  'Description, hint, topic...': 'Açıklama, ipucu, konu...',
  'Filter Questions': 'Soruları Filtrele', 'DIFFICULTY LEVEL': 'ZORLUK SEVİYESİ',
  'All': 'Hepsi', 'Clear': 'Temizle', 'Apply': 'Uygula',
  'Review': 'Gözden Geçir', 'NUMBER OF QUESTIONS': 'SORU SAYISI',
  'Export PDF': 'PDF Çıktı', 'Start': 'Başla', 'Warning': 'Uyarı',
  'No questions to review today matching these criteria.': 'Bu kriterlerde bugün gözden geçirilecek sorunuz yok.',
  'No suitable questions found.': 'Uygun soru bulunamadı.',
  'There are only': 'Bu kriterlerde yalnızca', 'questions matching these criteria.': 'soru var.',
  'Back': 'Geri', 'Finish': 'Bitir', 'Next': 'İleri',
  'You can write your solution here': 'Çözüm için buraya yazabilirsiniz',
  'Preparing Image': 'Görsel Hazırlanıyor',
  'Please wait.\nThis process may vary depending on your device\'s performance.': 'Lütfen bekleyin.\nBu işlem cihazınızın gücüne göre değişebilir.',
  'Error': 'Hata', 'An error occurred while generating the image:': 'Görsel oluşturulurken bir hata oluştu:',
  'AI Support': 'Yapay Zeka Desteği', 'What would you like to do with this question?': 'Bu soruyla ilgili ne yapmak istersin?',
  'Analyze Question': 'Soruyu Analiz Et', 'Generate Similar Question': 'Benzer Soru Üret',
  'Flash Questions AI Support': 'Flash Questions YZ Destek', 'Note:': 'Not:',
  'Prompt for AI:': 'Yapay Zeka İçin İstem (Prompt):',
  '': '', 'Answer Key': 'Cevap Anahtarı',
  'Today': 'Bugün', 'Tomorrow': 'Yarın', 'Overdue': 'Gecikti', 'Review: ': 'Tekrar: ',
  'Available': 'Mevcut', 'Select Random Questions': 'Rasgele Sorular Seç',
  'Practice without affecting review dates.': 'Tekrar tarihlerini etkilemeden pratik yap.',
  'Selected count cannot exceed available questions.': 'Seçilen soru sayısı mevcut sorulardan fazla olamaz.',
  'Title (Optional)': 'İsim / Başlık (İsteğe Bağlı)',
  'Question title...': 'Soru başlığı...',
  'Search by title...': 'İsim ile ara...',
  'Tags': 'ETİKETLER',
  'Add Tag': 'Etiket Ekle',
  'Custom Subject': 'Özel Ders',
  'Custom Difficulty': 'Özel Zorluk',
  'New Subject Name': 'Yeni Ders Adı',
  'New Difficulty Name': 'Yeni Zorluk Adı',
  'SOLUTION PHOTO': 'ÇÖZÜM FOTOĞRAFI',
  'Open-Ended Question': 'Açık Uçlu Soru',
  'Answer text...': 'Cevabınızı yazın...',
  'Start Review Today': 'Tekrara Bugünden Başla',
  'Submit': 'Gönder',
  'Add': 'Ekle',
  'Solution Photo': 'Çözüm Fotoğrafı',
  'Add Solution Photo': 'Çözüm Fotoğrafı Ekle',
  'APPEARANCE': 'GÖRÜNÜM',
  'Switch to Material Theme': 'Materyal Temaya Geçiş Yap',
  'If the app lags on your device, you can use this setting.': 'Eğer uygulama cihazınızda kasıyorsa bu ayarı kullanabilirsiniz.',
};

const _deMap = <String, String>{
  'Home': 'Startseite', 'Settings': 'Einstellungen', 'Select Language': 'Sprache auswählen',
  'App Language': 'App-Sprache', 'ARTIFICIAL INTELLIGENCE': 'KÜNSTLICHE INTELLIGENZ',
  'Delete All Questions': 'Alle Fragen löschen', 'No Questions': 'Keine Fragen',
  'Add First Question': 'Erste Frage hinzufügen',
  'Add questions you couldn\'t solve here.': 'Füge hier Fragen hinzu, die du nicht lösen konntest.',
  'math': 'Mathematik', 'physics': 'Physik', 'chemistry': 'Chemie', 'biology': 'Biologie',
  'nativeLang': 'Deutsch', 'literature': 'Literatur', 'history': 'Geschichte', 'geography': 'Geografie',
  'philosophy': 'Philosophie', 'foreignLang': 'Fremdsprache',
  'easy': 'Leicht', 'medium': 'Mittel', 'hard': 'Schwer',
  'Question': 'Frage', 'Days': 'Tage', 'No data': 'Keine Daten',
  'Review Questions': 'Fragen überprüfen',
  'questions listed': 'Fragen aufgelistet', 'Filter': 'Filtern',
  'No questions found matching these filters.': 'Keine Fragen für diese Filter gefunden.',
  'Delete Question': 'Frage löschen',
  'Are you sure you want to delete this question?': 'Sind Sie sicher, dass Sie diese Frage löschen möchten?',
  'Delete': 'Löschen', 'Cancel': 'Abbrechen',
  'LANGUAGE': 'SPRACHE', 'Analysis Prompt': 'Analyse-Prompt',
  'Similar Question Prompt': 'Ähnliche Fragen Prompt',
  'DATA MANAGEMENT': 'DATENVERWALTUNG', 'Saved Questions Count': 'Gespeicherte Fragen',
  'Export': 'Exportieren', 'Import': 'Importieren', 'DANGER ZONE': 'GEFAHRENZONE',
  'This action cannot be undone.': 'Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'OK': 'OK', 'Reset to Default': 'Auf Standard zurücksetzen', 'Save': 'Speichern',
  'All questions deleted.': 'Alle Fragen gelöscht.',
  'Reverted to default prompt.': 'Auf Standard-Prompt zurückgesetzt.',
  'Prompt saved.': 'Prompt gespeichert.',
  'An error occurred during export.': 'Beim Export ist ein Fehler aufgetreten.',
  'Invalid file. Please select a valid ZIP.': 'Ungültige Datei. Bitte wählen Sie eine gültige ZIP-Datei.',
  'An error occurred during import.': 'Beim Import ist ein Fehler aufgetreten.',
  'Add New Question': 'Neue Frage hinzufügen', 'Edit Question': 'Frage bearbeiten',
  'QUESTION PHOTO': 'FRAGENFOTO', 'Tap to add photo': 'Tippen, um ein Foto hinzuzufügen',
  'Take with Camera': 'Mit Kamera aufnehmen', 'Select from Gallery': 'Aus Galerie auswählen',
  'Add Photo': 'Foto hinzufügen', 'SUBJECT': 'FACH', 'DIFFICULTY': 'SCHWIERIGKEIT',
  'CORRECT ANSWER': 'RICHTIGE ANTWORT', 'NOTE (OPTIONAL)': 'NOTIZ (OPTIONAL)',
  'Description, hint, topic...': 'Beschreibung, Hinweis, Thema...',
  'Filter Questions': 'Fragen filtern', 'DIFFICULTY LEVEL': 'SCHWIERIGKEITSGRAD',
  'All': 'Alle', 'Clear': 'Löschen', 'Apply': 'Anwenden',
  'Review': 'Überprüfen', 'NUMBER OF QUESTIONS': 'ANZAHL DER FRAGEN',
  'Export PDF': 'PDF Export', 'Start': 'Start', 'Warning': 'Warnung',
  'No questions to review today matching these criteria.': 'Keine Fragen zur heutigen Überprüfung für diese Kriterien.',
  'No suitable questions found.': 'Keine passenden Fragen gefunden.',
  'There are only': 'Es gibt nur', 'questions matching these criteria.': 'Fragen für diese Kriterien.',
  'Back': 'Zurück', 'Finish': 'Beenden', 'Next': 'Weiter',
  'You can write your solution here': 'Sie können Ihre Lösung hier schreiben',
  'Preparing Image': 'Bild wird vorbereitet',
  'Please wait.\nThis process may vary depending on your device\'s performance.': 'Bitte warten.\nDieser Vorgang kann je nach Leistung Ihres Geräts variieren.',
  'Error': 'Fehler', 'An error occurred while generating the image:': 'Beim Erstellen des Bildes ist ein Fehler aufgetreten:',
  'AI Support': 'KI-Unterstützung', 'What would you like to do with this question?': 'Was möchten Sie mit dieser Frage tun?',
  'Analyze Question': 'Frage analysieren', 'Generate Similar Question': 'Ähnliche Frage generieren',
  'Flash Questions AI Support': 'Flash Questions KI-Unterstützung', 'Note:': 'Notiz:',
  'Prompt for AI:': 'Prompt für KI:',
  '': '', 'Answer Key': 'Lösungsschlüssel',
  'Today': 'Heute', 'Tomorrow': 'Morgen', 'Overdue': 'Überfällig', 'Review: ': 'Wdh: ',
  'Available': 'Verfügbar', 'Select Random Questions': 'Zufällige Fragen auswählen',
  'Practice without affecting review dates.': 'Üben, ohne die Wiederholungsdaten zu beeinflussen.',
  'Selected count cannot exceed available questions.': 'Die Anzahl darf die verfügbaren Fragen nicht überschreiten.',
  'Title (Optional)': 'Titel (Optional)',
  'Question title...': 'Fragentitel...',
  'Search by title...': 'Nach Titel suchen...',
  'Tags': 'TAGS',
  'Add Tag': 'Tag hinzufügen',
  'Custom Subject': 'Benutzerdefiniertes Fach',
  'Custom Difficulty': 'Benutzerdefinierte Schwierigkeit',
  'New Subject Name': 'Neuer Fachname',
  'New Difficulty Name': 'Neuer Schwierigkeitsname',
  'SOLUTION PHOTO': 'LÖSUNGSFOTO',
  'Open-Ended Question': 'Offene Frage',
  'Answer text...': 'Antwort eingeben...',
  'Start Review Today': 'Heute mit Überprüfung beginnen',
  'Submit': 'Einreichen',
  'Add': 'Hinzufügen',
  'Solution Photo': 'Lösungsfoto',
  'Add Solution Photo': 'Lösungsfoto hinzufügen',
  'APPEARANCE': 'ERSCHEINUNGSBILD',
  'Switch to Material Theme': 'Zum Material Design wechseln',
  'If the app lags on your device, you can use this setting.': 'Wenn die App auf Ihrem Gerät ruckelt, können Sie diese Einstellung verwenden.',
};

extension StringLoc on String {
  String get t {
    if (appLang.value == AppLang.tr) return _trMap[this] ?? this;
    if (appLang.value == AppLang.de) return _deMap[this] ?? this;
    return this;
  }
}
